version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    volumes:
      - ./app/db_data:/app/db_data
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
